"""add_file_hash

Revision ID: 3e2e33a40151
Revises: 85df0982b9f3
Create Date: 2026-03-04 15:01:09.390574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2e33a40151'
down_revision: Union[str, Sequence[str], None] = '85df0982b9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'file', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='unique')
    op.drop_column('file', 'hash')
    # ### end Alembic commands ###
