"""project

Revision ID: 4402f991de3e
Revises: cd1b8a750c04
Create Date: 2026-03-12 11:51:03.892264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4402f991de3e'
down_revision: Union[str, Sequence[str], None] = 'cd1b8a750c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_project_author_id'), 'project', ['author_id'], unique=False)
    op.create_index(op.f('ix_project_created_at'), 'project', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_is_removed'), 'project', ['is_removed'], unique=False)
    op.create_index(op.f('ix_project_organization_id'), 'project', ['organization_id'], unique=False)
    op.create_index(op.f('ix_project_updated_at'), 'project', ['updated_at'], unique=False)
    op.create_unique_constraint(None, 'organization', ['id'])
    op.create_unique_constraint(None, 'organization_member', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_member', type_='unique')
    op.drop_constraint(None, 'organization', type_='unique')
    op.drop_index(op.f('ix_project_updated_at'), table_name='project')
    op.drop_index(op.f('ix_project_organization_id'), table_name='project')
    op.drop_index(op.f('ix_project_is_removed'), table_name='project')
    op.drop_index(op.f('ix_project_created_at'), table_name='project')
    op.drop_index(op.f('ix_project_author_id'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
