"""init_db

Revision ID: 7149472123f8
Revises:
Create Date: 2026-03-17 12:35:18.460757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7149472123f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('is_confirmed', sa.Boolean(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('avatar_file_id', sa.Uuid(), nullable=True),
        sa.Column('is_removed', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_avatar_file_id'), 'user', ['avatar_file_id'], unique=False)
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_is_removed'), 'user', ['is_removed'], unique=False)
    op.create_index(op.f('ix_user_updated_at'), 'user', ['updated_at'], unique=False)

    op.create_table(
        'file',
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('size', sa.Integer(), nullable=False),
        sa.Column('content_type', sa.String(), nullable=False),
        sa.Column('hash', sa.String(), nullable=True),
        sa.Column('author_id', sa.Uuid(), nullable=False),
        sa.Column('is_removed', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_author_id'), 'file', ['author_id'], unique=False)
    op.create_index(op.f('ix_file_created_at'), 'file', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_is_removed'), 'file', ['is_removed'], unique=False)
    op.create_index(op.f('ix_file_updated_at'), 'file', ['updated_at'], unique=False)

    op.create_foreign_key(
        'user_avatar_file_id_fkey',
        'user',
        'file',
        ['avatar_file_id'],
        ['id'],
        ondelete='SET NULL',
    )

    op.create_table('entity_event',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('producer_id', sa.Uuid(), nullable=True),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_event_created_at'), 'entity_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_entity_event_entity'), 'entity_event', ['entity'], unique=False)
    op.create_index(op.f('ix_entity_event_entity_id'), 'entity_event', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_event_producer_id'), 'entity_event', ['producer_id'], unique=False)
    op.create_table('organization',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('enter_token', sa.String(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_author_id'), 'organization', ['author_id'], unique=False)
    op.create_index(op.f('ix_organization_created_at'), 'organization', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_enter_token'), 'organization', ['enter_token'], unique=True)
    op.create_index(op.f('ix_organization_is_removed'), 'organization', ['is_removed'], unique=False)
    op.create_index(op.f('ix_organization_updated_at'), 'organization', ['updated_at'], unique=False)
    op.create_table('organization_member',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_organization_member_user')
    )
    op.create_index(op.f('ix_organization_member_created_at'), 'organization_member', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_member_is_removed'), 'organization_member', ['is_removed'], unique=False)
    op.create_index(op.f('ix_organization_member_organization_id'), 'organization_member', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_member_updated_at'), 'organization_member', ['updated_at'], unique=False)
    op.create_index(op.f('ix_organization_member_user_id'), 'organization_member', ['user_id'], unique=False)
    op.create_table('project',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_author_id'), 'project', ['author_id'], unique=False)
    op.create_index(op.f('ix_project_created_at'), 'project', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_is_removed'), 'project', ['is_removed'], unique=False)
    op.create_index(op.f('ix_project_organization_id'), 'project', ['organization_id'], unique=False)
    op.create_index(op.f('ix_project_updated_at'), 'project', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_updated_at'), table_name='project')
    op.drop_index(op.f('ix_project_organization_id'), table_name='project')
    op.drop_index(op.f('ix_project_is_removed'), table_name='project')
    op.drop_index(op.f('ix_project_created_at'), table_name='project')
    op.drop_index(op.f('ix_project_author_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_organization_member_user_id'), table_name='organization_member')
    op.drop_index(op.f('ix_organization_member_updated_at'), table_name='organization_member')
    op.drop_index(op.f('ix_organization_member_organization_id'), table_name='organization_member')
    op.drop_index(op.f('ix_organization_member_is_removed'), table_name='organization_member')
    op.drop_index(op.f('ix_organization_member_created_at'), table_name='organization_member')
    op.drop_table('organization_member')
    op.drop_index(op.f('ix_organization_updated_at'), table_name='organization')
    op.drop_index(op.f('ix_organization_is_removed'), table_name='organization')
    op.drop_index(op.f('ix_organization_enter_token'), table_name='organization')
    op.drop_index(op.f('ix_organization_created_at'), table_name='organization')
    op.drop_index(op.f('ix_organization_author_id'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_entity_event_producer_id'), table_name='entity_event')
    op.drop_index(op.f('ix_entity_event_entity_id'), table_name='entity_event')
    op.drop_index(op.f('ix_entity_event_entity'), table_name='entity_event')
    op.drop_index(op.f('ix_entity_event_created_at'), table_name='entity_event')
    op.drop_table('entity_event')
    op.drop_index(op.f('ix_user_updated_at'), table_name='user')
    op.drop_index(op.f('ix_user_is_removed'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_index(op.f('ix_user_avatar_file_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_file_updated_at'), table_name='file')
    op.drop_index(op.f('ix_file_is_removed'), table_name='file')
    op.drop_index(op.f('ix_file_created_at'), table_name='file')
    op.drop_index(op.f('ix_file_author_id'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
