"""add_file

Revision ID: 85df0982b9f3
Revises: aaa7eda9c0bc
Create Date: 2026-03-03 13:02:32.035757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85df0982b9f3'
down_revision: Union[str, Sequence[str], None] = 'aaa7eda9c0bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_file_author_id'), 'file', ['author_id'], unique=False)
    op.create_index(op.f('ix_file_created_at'), 'file', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_is_removed'), 'file', ['is_removed'], unique=False)
    op.create_index(op.f('ix_file_updated_at'), 'file', ['updated_at'], unique=False)
    op.create_unique_constraint(None, 'entity_event', ['id'])
    op.add_column('user', sa.Column('avatar_file_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_user_avatar_file_id'), 'user', ['avatar_file_id'], unique=False)
    op.create_foreign_key(None, 'user', 'file', ['avatar_file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_avatar_file_id'), table_name='user')
    op.drop_column('user', 'avatar_file_id')
    op.drop_constraint(None, 'entity_event', type_='unique')
    op.drop_index(op.f('ix_file_updated_at'), table_name='file')
    op.drop_index(op.f('ix_file_is_removed'), table_name='file')
    op.drop_index(op.f('ix_file_created_at'), table_name='file')
    op.drop_index(op.f('ix_file_author_id'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
