"""add_entity_event

Revision ID: aaa7eda9c0bc
Revises: 9b4a06401b6e
Create Date: 2026-03-02 14:59:14.413358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aaa7eda9c0bc'
down_revision: Union[str, Sequence[str], None] = '9b4a06401b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_event',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('producer_id', sa.Uuid(), nullable=True),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_entity_event_created_at'), 'entity_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_entity_event_entity'), 'entity_event', ['entity'], unique=False)
    op.create_index(op.f('ix_entity_event_entity_id'), 'entity_event', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_event_producer_id'), 'entity_event', ['producer_id'], unique=False)
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_entity_event_producer_id'), table_name='entity_event')
    op.drop_index(op.f('ix_entity_event_entity_id'), table_name='entity_event')
    op.drop_index(op.f('ix_entity_event_entity'), table_name='entity_event')
    op.drop_index(op.f('ix_entity_event_created_at'), table_name='entity_event')
    op.drop_table('entity_event')
    # ### end Alembic commands ###
