"""organization_models

Revision ID: cd1b8a750c04
Revises: 3e2e33a40151
Create Date: 2026-03-11 17:28:53.423394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1b8a750c04'
down_revision: Union[str, Sequence[str], None] = '3e2e33a40151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_organization_author_id'), 'organization', ['author_id'], unique=False)
    op.create_index(op.f('ix_organization_created_at'), 'organization', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_is_removed'), 'organization', ['is_removed'], unique=False)
    op.create_index(op.f('ix_organization_updated_at'), 'organization', ['updated_at'], unique=False)
    op.create_table('organization_member',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_organization_member_user')
    )
    op.create_index(op.f('ix_organization_member_created_at'), 'organization_member', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_member_is_removed'), 'organization_member', ['is_removed'], unique=False)
    op.create_index(op.f('ix_organization_member_organization_id'), 'organization_member', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_member_updated_at'), 'organization_member', ['updated_at'], unique=False)
    op.create_index(op.f('ix_organization_member_user_id'), 'organization_member', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_member_user_id'), table_name='organization_member')
    op.drop_index(op.f('ix_organization_member_updated_at'), table_name='organization_member')
    op.drop_index(op.f('ix_organization_member_organization_id'), table_name='organization_member')
    op.drop_index(op.f('ix_organization_member_is_removed'), table_name='organization_member')
    op.drop_index(op.f('ix_organization_member_created_at'), table_name='organization_member')
    op.drop_table('organization_member')
    op.drop_index(op.f('ix_organization_updated_at'), table_name='organization')
    op.drop_index(op.f('ix_organization_is_removed'), table_name='organization')
    op.drop_index(op.f('ix_organization_created_at'), table_name='organization')
    op.drop_index(op.f('ix_organization_author_id'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
