"""organization_enter_token

Revision ID: d3c64a243d47
Revises: 4402f991de3e
Create Date: 2026-03-15 01:16:28.657783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c64a243d47'
down_revision: Union[str, Sequence[str], None] = '4402f991de3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('enter_token', sa.String(), nullable=True))
    op.execute("""
            UPDATE organization
            SET enter_token = gen_random_uuid()::text
            WHERE enter_token IS NULL
        """)
    op.alter_column(
            'organization',
            'enter_token',
            nullable=False
        )


    op.create_index(op.f('ix_organization_enter_token'), 'organization', ['enter_token'], unique=True)
    op.create_unique_constraint(None, 'project', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_index(op.f('ix_organization_enter_token'), table_name='organization')
    op.drop_column('organization', 'enter_token')
    # ### end Alembic commands ###
